### ISSUE TITLE
ERROR 未绑定属性[printHTML]

### ISSUE THREAD

**Issue by koyaja** [laixiangran/e-ngx-print#2]
I would use the plugin here is the error that see,
vendor.dll.js:1512 ERROR 未绑定属性[printHTML]

**Comment by laixiangran** [comment]
printHTML is an input attribute that indicates what you want to print(string or HTMLElement)

**Comment by koyaja** [comment]
hello thank she work and if If it wants to use bootstrap of the project or the node module it does not work `essence-ng2-print.component.js:35 GET http://localhost:9000/node_modules/bootstrap/dist/css/bootstrap.min.css `

**Comment by laixiangran** [comment]
Preferably write absolute path, such as http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css.If it is your own service, CSS must be in assets, such as http://youservice/assets/bootstrap/3.3.7/css/bootstrap.min.css

**Comment by koyaja** [comment]
Please how I automatically retrieve the address of my service with angular 2 and put in parameter Thanks
