### ISSUE TITLE
页面和预览的页面不一致.

### ISSUE THREAD

**Issue by gyyxiaogao** [laixiangran/e-ngx-print#6]
![snip20171204_2](https://user-images.githubusercontent.com/16957066/33542728-3c0e0b88-d90f-11e7-882a-6db1242764fd.png)

**Comment by laixiangran** [comment]
你样式正确应用了吗？

**Comment by unaJJJ** [comment]
为什么样式在分页显示的那里 出现错误？  在那一行文本的中间多了一条线？

**Comment by laixiangran** [comment]
@unaJJJ 你这样我无法给你回答，你截图我看看或者代码贴出来
