### ISSUE TITLE
感想分享，请教2个问题，打印时可以选择不要页眉和页码吗？另外，可以不预览直接打印吗？

### ISSUE THREAD

**Issue by woshiyifadaguangtou** [laixiangran/e-ngx-print#7]
非常感谢分享您做的这个打印控件，我现在想用来打印收据，在打印的时候会在左上角输出时间，右下角输出URL，还有页码，这些可以隐藏吗？还有可以不预览直接打印吗?

**Comment by laixiangran** [comment]
@woshiyifadaguangtou 第一个问题：只能在浏览器出来打印的那个页面自己设置。第二个问题目前没实现。
