### ISSUE TITLE
Allowing styles to cascade rather than being replaced entirely for print

### ISSUE THREAD

**Issue by toddprouty** [laixiangran/e-ngx-print#8]
Is there any way to make use of the cascade and allow a printed div to inherit global styles? I would like to override _some_ styles for printing while keeping most of them intact. It appears there is no way to do this as all existing styles are stripped away and only those in `[printCSS]` or `[printStyle]` are applied. Am I missing something?

**Comment by laixiangran** [comment]
@toddprouty You must use [printCSS] or [printStyle] to reset the style of the printed div.
