### ISSUE TITLE
请问引入的第三方组件的css路径该怎么写？比如primeng的

### ISSUE THREAD

**Issue by gh0stking** [laixiangran/e-ngx-print#9]
我是这样写的，但是点击打印之后报404
`this.printCSS = [
      "../../node_modules/font-awesome/css/font-awesome.min.css",
      "../../node_modules/primeng/resources/themes/omega/theme.css",
      "../../node_modules/primeng/resources/primeng.min.css",
    ];`

**Comment by laixiangran** [comment]
"../../node_modules/font-awesome/css/font-awesome.min.css"这样的路径肯定不行，你想想你发布之后会有这个node_modules文件夹吗？建议把这几个css路径写成能访问的绝对路径
